name: washeuteessen-ui
version: 0.1
description: Helm Deployment Descriptions for washeuteessen-UI
keywords:
  - washeuteessen
home: https://github.com/washeuteessen
sources:
  - https://github.com/washeuteessen/washeuteessen-ui
