kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.app_name | quote }}
spec:
  host: {{ .Values.application_domain | quote }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: {{ .Values.name | quote }}